#!/bin/sh

userresources="$XDG_CONFIG_HOME/X11/.Xresources"
usermodmap="$XDG_CONFIG_HOME/X11/.Xmodmap"
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"

# merge in defaults and keymaps
if [[ -f "$sysresources" ]]; then
    xrdb -merge "$sysresources"
fi

if [[ -f "$sysmodmap" ]]; then
    xmodmap "$sysmodmap"
fi

if [[ -f "$userresources" ]]; then
    xrdb -merge "$userresources"
fi

if [[ -f "$usermodmap" ]]; then
    xmodmap "$usermodmap"
fi


### CUSTOM
# Disable keyboard repeat rate; that is, if you hold down a key, it won't be
# counted multiple times
xset r off

# Make CapsLock an additional ESC
setxkbmap -option caps:escape

# Be easier on the eyes
exec redshift -t 4200:2000 -g 0.8 -m randr &

# feh for wallpaper + picom as compositer
WALLPAPER="${XDG_CONFIG_HOME}/i3/wallpaper.png"
exec feh --no-fehbg --bg-scale ${WALLPAPER} &
exec picom &
exec xrandr --output eDP --set TearFree on &

# Execute a custom script that reminds you to get up and exercise
[[ -f "$HOME/bin/takeabreak" ]] && exec "$HOME/bin/takeabreak" &

# Start notification manager
exec dunst &

# Finally, execute the graphical environment
exec i3
