# XDG stuffs
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CACHE_HOME="${HOME}/.cache"

# Set location where zsh dotfiles are located
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
